import '../styles/styles.scss';
import {Providers} from '@/store/provider';

import {library} from '@fortawesome/fontawesome-svg-core'
import {fas} from '@fortawesome/free-solid-svg-icons'

import Header from '@/components/header';
import Footer from "@/components/footer";
import {Suspense} from "react";
import Loading from "@/app/loading";

library.add(fas)

export const metadata = {
  title: 'Welcome to shop-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({children}: { children: any }) {
  return (
    <html lang="en">
    <body>
    <Providers>
      <Header/>
      <Suspense fallback={<Loading/>}>
        {children}
      </Suspense>
      <Footer/>
    </Providers>
    </body>
    </html>
  );
}
